@startuml StateDiagram

hide empty description
skinparam monochrome true

state "TitleScreenState" as TSS
state "InstructionsState" as IS
state "PlayState" as PS
state "PauseState" as PAS
state "VictoryState" as VS
state "GameOverState" as GOS
state Menu <<choice>>

[*] --> TSS

TSS --> Menu
Menu --> IS: Instructions
Menu --> PS: Play

IS --> TSS: Return to Menu

PS --> PAS: Press ESC
PAS --> PS: Press ESC
PAS --> TSS: Quit to Menu

PS --> VS: Quota Met + Exit Reached
PS --> GOS: Caught or Time Expired

GOS --> PS: Press Enter (Retry)

VS --> TSS: Return to Menu

@enduml