@startuml StateDiagram

hide empty description
skinparam monochrome true

state "TitleScreenState" as TSS
state "InstructionsState" as IS
state "PlayState" as PS
state "PauseState" as PAS
state "LevelCompleteState" as LCS
state "VictoryState" as VS
state "GameOverState" as GOS
state Menu <<choice>>
state PlayAgain <<choice>>

[*] --> TSS

TSS --> Menu
Menu --> IS: Instructions
Menu --> PS: Play

PS --> PAS: Press ESC
PAS --> PS: Press ESC

PS --> LCS: Quota Met + Exit Reached
PS --> GOS: Caught or Time Expired

LCS --> PlayAgain: Continue?
GOS --> PlayAgain: Retry?

PlayAgain --> TSS: Return to Menu
PlayAgain --> PS: Next Level / Retry

LCS --> VS: All Levels Complete

VS --> TSS: Return to Menu

@enduml